name: Run Who Am I Script

on: [push, workflow_dispatch]

jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Make script executable and run it
        run: |
          chmod +x 1-who_am_i
          ./1-who_am_i
